### ISSUE TITLE
什么时候升级flutter3.0呢

### ISSUE THREAD

**Issue by popo5211105** [jhflovehqy/flutter_bolg_manage#23]
什么时候升级flutter3.0呢，期待

**Comment by FoneG** [comment]
期待

**Comment by 79121262** [comment]
可以的话让我来提交 3.0 升级后的代码

**Comment by YuQi9797** [comment]
> 可以的话让我来提交 3.0 升级后的代码

兄弟有说法？

**Comment by 79121262** [comment]
> > 可以的话让我来提交 3.0 升级后的代码
> 
> 兄弟有说法？

> 项目不错， 我写了3.0 的代码

**Comment by YuQi9797** [comment]
> > > 可以的话让我来提交 3.0 升级后的代码
> > 
> > 
> > 兄弟有说法？
> 
> > 项目不错， 我写了3.0 的代码

能否开源下呢？hxd

**Comment by 79121262** [comment]
可以

**Comment by 79121262** [comment]
> > > > 可以的话让我来提交 3.0 升级后的代码
> > > 
> > > 
> > > 兄弟有说法？
> > 
> > 
> > > 项目不错， 我写了3.0 的代码
> 
> 能否开源下呢？hxd

可以

**Comment by YuQi9797** [comment]
> > > > > 可以的话让我来提交 3.0 升级后的代码
> > > > 
> > > > 
> > > > 兄弟有说法？
> > > 
> > > 
> > > > 项目不错， 我写了3.0 的代码
> > 
> > 
> > 能否开源下呢？hxd
> 
> 可以

能否给了链接，万分感谢！

**Comment by 79121262** [comment]
> > > > > > 可以的话让我来提交 3.0 升级后的代码
> > > > > 
> > > > > 
> > > > > 兄弟有说法？
> > > > 
> > > > 
> > > > > 项目不错， 我写了3.0 的代码
> > > 
> > > 
> > > 能否开源下呢？hxd
> > 
> > 
> > 可以
> 
> 能否给了链接，万分感谢！

https://github.com/jhflovehqy/flutter_bolg_manage/pull/24

**Comment by YuQi9797** [comment]
> > > > > > > 可以的话让我来提交 3.0 升级后的代码
> > > > > > 
> > > > > > 
> > > > > > 兄弟有说法？
> > > > > 
> > > > > 
> > > > > > 项目不错， 我写了3.0 的代码
> > > > 
> > > > 
> > > > 能否开源下呢？hxd
> > > 
> > > 
> > > 可以
> > 
> > 
> > 能否给了链接，万分感谢！
> 
> #24

你好，我下下来存在问题：
```
Exception in thread "main" java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1474)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1482)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1320)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1282)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Exception: Gradle task assembleDebug failed with exit code 1

```

**Comment by 79121262** [comment]
> > > > > > > 可以的话让我来提交 3.0 升级后的代码
> > > > > > 
> > > > > > 
> > > > > > 兄弟有说法？
> > > > > 
> > > > > 
> > > > > > 项目不错， 我写了3.0 的代码
> > > > 
> > > > 
> > > > 能否开源下呢？hxd
> > > 
> > > 
> > > 可以
> > 
> > 
> > 能否给了链接，万分感谢！
> 
> #24

删掉 .gradle 保持网络畅通重新试验下，我这边的环境是可以跑起来的

**Comment by YuQi9797** [comment]
> > > > > > > > 可以的话让我来提交 3.0 升级后的代码
> > > > > > > 
> > > > > > > 
> > > > > > > 兄弟有说法？
> > > > > > 
> > > > > > 
> > > > > > > 项目不错， 我写了3.0 的代码
> > > > > 
> > > > > 
> > > > > 能否开源下呢？hxd
> > > > 
> > > > 
> > > > 可以
> > > 
> > > 
> > > 能否给了链接，万分感谢！
> > 
> > 
> > #24
> 
> 删掉 .gradle 保持网络畅通重新试验下，我这边的环境是可以跑起来的

可以了！ 谢谢！

**Comment by YuQi9797** [comment]
老哥能留个你的联系方式吗？ 关于部分代码问题，我希望能够请教一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月15日(星期三) 上午10:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jhflovehqy/flutter_bolg_manage] 什么时候升级flutter3.0呢 (Issue #23)





       
可以的话让我来提交 3.0 升级后的代码
  
兄弟有说法？
   
项目不错， 我写了3.0 的代码
   
能否开源下呢？hxd
  
可以
  
能否给了链接，万分感谢！
  
#24
